name: integration-test01
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      # https://github.com/cypress-io/github-action
      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          record: true
          start: npm run serve
          working-directory: frontend
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: 688b7724-86f6-4534-b758-1aabaa43b34c
